### PR TITLE
Subcommand autocompletion

### PR DESCRIPTION
**Pull request by CortexPE**
Subcommands now autocomplete, complete with the descriptions... the only major issue is the arguments aren't appearing anymore.

### CODE REVIEW

**Comment by CortexPE** [comment]
just noticed... this also has the selector stuff.... reee

**Comment by CortexPE** [comment]
The issue might be related to #14 

the client might not be showing commands with names that have non-alphanumeric characters...

Spaces and slashes aren't alphanumeric.

**Comment by lukeeey** [comment]
Also this doesnt seem to display correctly like vanilla

**Comment by CortexPE** [comment]
What is the difference between the two?

**Comment by lukeeey** [comment]
Here is your currently implementation
https://photos.app.goo.gl/Pp8jr3pfJFfwCWZo8

Obviously arguments dont work but there doesnt seem to be a blank space between the base command description and the subcommands. This leads me to believe that its registered as a seperate command.

---

https://photos.app.goo.gl/fcdf9EecuC3KpcR27

Here are some examples of vanilla commands. Notice the blank space?

**Comment by CortexPE** [comment]
I'll try adding a trailing space on the end

**Comment by lukeeey** [comment]
@CortexPE I meant the blank line

**Comment by CortexPE** [comment]
The blank line is probably there to divide the commands from the
arguments... Before the subcommand auto complete was on this separate
branch, there was no blank lines as well.

Can you dump the AvailableCommandsPacket the vanilla server sends?

I think it can be done with wireshark or smth then we should just peice
together a buffer that isn't encapsulated by RakNet then feed it to PM to
decode it.

I haven't tried tho 😂

**Comment by CortexPE** [comment]
nice rebase smfh REEEE

**Comment by CortexPE** [comment]
This is a mess, already resolved anyway

**Pull request closed without merging**
