### PR TITLE
Allow multiple args to be set at the same position

### PR DESCRIPTION
**Pull request by JackMD**
## Description

This PR makes it possible for more than one argument with different names be passed at the same position. Previously whichever argument was passed first was passed to the client. Now the virion decides which argument to pass to the user based on the users input.

### CODE REVIEW

**Comment by CortexPE** [comment]
Any tests?

**Comment by JackMD** [comment]
Have two args with different name at the same position. You will notice only a single arg gets passed and not the other one. This is undesirable especially for the case of help command where you have two args one IntegerArg name `page` and other StringArg with name `command`. Upon my testings, only `command` arg was being passed and `page` arg being ignored. But this PR fixes that.

**Comment by JackMD** [comment]
### Test
A help command with two args with different names but at the same position:

```php
$this->registerArgument(0, new IntegerArgument("page", true));
$this->registerArgument(0, new StringEnumArgument("command", true));//this class is extended ofc to fit in the enum values
```

### Overview

Okay so I looked over this issue again. Turns out the problem is a bit different. So Commando indeed passes both the arguments but it converts the output into an array like so.

arrrrr

This behavior of commando is defined no where in the README or the wiki. And so it breaks the users previous assumption of getting the arg by doing `$args["page"]`. The user now has to do `$args["page][0]` or use a loop to iterate over it as done in Hierarchy. 

In this test as you can clearly see I passed in two args at the same position but having different names. Indeed both the arguments are passed but why, have the output, in the form of an array when Commando only passes one argument to the user? As shown in the pic attached below (and the one above).

asa

As you can clearly tell, only one argument gets passed to the user depending upon what he entered but it is converted into an array which is not needed at all since only one argument will be passed either way. 

This PR fixes this undefined behavior by passing the required argument without the array. As seen in the pics attached below. Only the required arg based on the users input will be passed.

re

And so the desired result is achieved.

**Comment by thebigsmileXD** [comment]
Neat test and addition. This would mean one would have to check what returned arg is set, but that is kind of the same thing as handling it in vanilla pmmp, right?
In pmmp it would be
```php
switch($args[0])
case "help"
case "page"
```
What would be the efficient way of doing this using Commando after this command?

**Comment by CortexPE** [comment]
What if there's two arguments at the same place with the same name?

**Comment by CortexPE** [comment]
One of the issues is if two arguments support the given input

**Comment by JackMD** [comment]
> What if there's two arguments at the same place with the same name?

Two arguments `int` and `string` or `string` and `string`, either both optional or not or if one is optional and the other is not or vice versa, passed at the same place and having same or different name, have exactly the same output as shown above. Depending on what the user entered i.e. a string or an int, only one argument gets passed **only one**.

And so I say it once more, when only **one** argument is passed then there is no need for nesting it in an array.

**Comment by JackMD** [comment]
@thebigsmileXD no you got it all wrong. The argument is not passed like `$args[0]["command"]` or `$args[0]["page"]` instead it is passed as `$args["command"][0]` or `$args["page"][0]`.

**Comment by JackMD** [comment]
Adding to the previous reply, this PR would eliminate the need of adding that `[0]`. Its totally unnecessary and uncalled for to have that `[0]` at the end of the sequence when only **one** argument is passed.

**Comment by JackMD** [comment]
> One of the issues is if two arguments support the given input

In either case they will be supported. In my testing I had an `StringEnumArg` with the value `help` and a `RawStringArg` both having same name and passed at the same position. The current implementation would just pass it as `$args["command"][0] => "help` when I used `/rank help help` and would pass `$args["command"][0] => "hel` when I used `/rank help hel`. 

With the changes done through this PR it passed  `$args["command"] => "help` when I used `/rank help help` and would pass `$args["command"] => "hel` when I used `/rank help hel`. 

Commando is capable of deciding which argument to pass to the user depending on the users input. Only **argument** gets passed either way.

**Comment by CortexPE** [comment]
Shouldn't $args["command"] only be the first argument which is "help"?
Since it was registered at position 0

**Comment by JackMD** [comment]
Didnt quite get that 🙄

**Comment by CortexPE** [comment]
In your example `/rank help hel`, the $args["command"] argument which was
at the first position (0) had the value of "hel" instead of "help"

**Comment by JackMD** [comment]
Thats because /rank is the main command and help is its subcommand. Sorry I should had cleared that out.

**Comment by CortexPE** [comment]
I suggest bumping the major version as this breaks a significant behavior

**Pull request merged**
