### PR TITLE
PocketMine API 5 Changes

### PR DESCRIPTION
**Pull request by jasonw4331**
I recommend accepting PR #41 following immediately following this.

### CODE REVIEW

**Comment by TacoError** [comment]
Thanks Jason, I was just about to do this myself, thank God I don't have to waste my time

**Comment by TacoError** [comment]
You got a BuyMeACoffe?

**Comment by NhanAZ** [comment]
@CortexPE Merge plz

**Review by NhanAZ — APPROVED** [review]

**Comment by inxomnyaa** [comment]
It will take a while for me to validate those changes, i haven't checked out PM5 so far.
Summer = Nature time for me, especially this year :)

**Review by didntpot — APPROVED** [review]

**Comment by didntpot** [comment]
@jasonw4331 this has been outdated since the [1.20.10 update](https://github.com/pmmp/BedrockProtocol/commit/7fe653370a2729850d2ccaf07f7dadd964ce2927#diff-5b1bcdbcce1693554b8fddb9922837ec7696ed6081e1664207ce38b61ebceb69).

**Pull request closed without merging**
